
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts4-server-deployment
  labels:
    app: ts4-server
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ts4-server
  template:
    metadata:
      labels:
        app: ts4-server
    spec:
      imagePullSecrets:
      - name: timeweb-registry-secret

      containers:
      - name: ts4-server
        
        image: dbe81550-wise-chickadee.registry.twcstorage.ru/ts4-server:main
        command: ["/usr/local/bin/server", "--mode", "production", "--role", "monolith"]

        imagePullPolicy: Always 

        ports:
        - containerPort: 8080 
        - containerPort: 8081 
        - containerPort: 8082 

        envFrom:
        - configMapRef:
            name: serverpod-config-ts4 
        
        env:
        - name: SERVERPOD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-ts4 
              key: database-password 
        - name: SERVERPOD_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-ts4
              key: redis-password
        - name: SERVERPOD_SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-ts4
              key: service-secret

        readinessProbe:
          httpGet:
            path: / 
            port: 8082
          initialDelaySeconds: 20 
          periodSeconds: 15     

        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60 
          periodSeconds: 30

    