name: Build and Push Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-push-and-update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Нужны права на запись для коммита изменений
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Нужно использовать токен с правами на запись, чтобы закоммитить изменения
        with:
          token: ${{ secrets.PAT_TOKEN }} # Создайте Personal Access Token с правами repo и сохраните в секретах

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dbe81550-wise-chickadee.registry.twcstorage.ru/ts4-server
          tags: |
            type=sha,prefix=,format=short

      - name: Log in to Timeweb Container Registry
        uses: docker/login-action@v3
        with:
          registry: dbe81550-wise-chickadee.registry.twcstorage.ru
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ts4_server
          file: ./ts4_server/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Kubernetes manifests with new image tag
        run: |
          # Используем тег, сгенерированный на шаге 'meta'
          NEW_TAG=${{ steps.meta.outputs.version }}
          echo "New image tag: $NEW_TAG"
          sed -i 's|image: dbe81550-wise-chickadee.registry.twcstorage.ru/ts4-server:.*|image: dbe81550-wise-chickadee.registry.twcstorage.ru/ts4-server:'"$NEW_TAG"'|g' ts4_server/k8s/deployment.yaml
          sed -i 's|image: dbe81550-wise-chickadee.registry.twcstorage.ru/ts4-server:.*|image: dbe81550-wise-chickadee.registry.twcstorage.ru/ts4-server:'"$NEW_TAG"'|g' ts4_server/k8s/job.yaml

      - name: Commit and push manifest changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ts4_server/k8s/deployment.yaml ts4_server/k8s/job.yaml
          # Проверяем, есть ли изменения, чтобы не делать пустых коммитов
          if ! git diff --staged --quiet; then
            git commit -m "ci: update image tag to ${{ steps.meta.outputs.version }}"
            git push
          else
            echo "No changes to commit."
          fi